# Generated by Django 4.0.1 on 2022-05-01 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='null', max_length=500)),
                ('text', models.TextField(default='null')),
                ('description', models.TextField(default='null')),
                ('price', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('availability', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
