# Generated by Django 4.0.1 on 2022-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
