# Generated by Django 4.0.1 on 2022-05-02 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_products_category'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('products', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmer.products')),
                ('public_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='public.registration')),
            ],
        ),
    ]
